# Generated by Django 5.2.1 on 2025-05-29 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Something',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=122, verbose_name='title')),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Something',
                'verbose_name_plural': 'Something',
            },
        ),
    ]
